# Generated by Django 4.1.7 on 2023-03-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="distric",
            new_name="district",
        ),
        migrations.AlterField(
            model_name="address",
            name="zipCode",
            field=models.CharField(max_length=9),
        ),
    ]
