# Generated by Django 4.1.7 on 2023-03-08 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("stock", models.PositiveIntegerField()),
                ("category", models.CharField(max_length=30)),
                ("isActive", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
